---
varReference:
  - kind: StatefulSet
    path: spec/template/spec/containers/args
  # - kind: StatefulSet
  #   path: spec/template/spec/containers/env/value
  - kind: StatefulSet
    path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
