apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../single-pod/common
- statefulset.yaml

configurations:
- kustomizeconfig.yaml

vars:
- fieldref:
    fieldPath: metadata.name
  name: SECRET_NAME
  objref:
    apiVersion: v1
    kind: Secret
    name: freeipa
