apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./common
- pod-main.yaml

configurations:
- kustomizeconfig.yaml

images:
- name: workload
  newName: quay.io/freeipa/freeipa-openshift-container
  newTag: latest
