---
apiVersion: v1
kind: Pod
metadata:
  name: freeipa-main
  annotations:
    openshift.io/scc: freeipa
  labels:
    app: freeipa
    role: main
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: freeipa-workload
  containers:
  - name: main
    image: workload
    imagePullPolicy: Always
    # SYSTEMD_LOG_LEVEL=debug INIT_WRAPPER=1 DEBUG_TRACE=2 PASSWORD=Secret123 NAMESPACE=freeipa SYSTEMD_OFFLINE=1 podman run -it quay.io/freeipa/freeipa-openshift-container:freeipa-server no-exit ipa-server-install -U --realm APPS.MYKUBE.KARMALABS.COM --ca-subject="CN=freeipa-11111, O=APPS.MYKUBE.KARMALABS.COM" --no-ntp --no-sshd --no-ssh --verbose
    # podman run -it -e SYSTEMD_LOG_LEVEL=debug -e INIT_WRAPPER=1 -e DEBUG_TRACE=2 -e PASSWORD=Secret123 -e NAMESPACE=freeipa -e SYSTEMD_OFFLINE=1  quay.io/freeipa/freeipa-openshift-container:freeipa-server no-exit ipa-server-install -U --realm APPS.MYKUBE.KARMALABS.COM --ca-subject="CN=freeipa-11111, O=APPS.MYKUBE.KARMALABS.COM" --no-ntp --no-sshd --no-ssh --verbose
    command:
    - /usr/local/sbin/init
    args:
    - no-exit
    - ipa-server-install
    - -U
    # TODO Checkout this fields before deploy
    # TODO Define variable IPA_SERVER_REALM
    - --realm
    # - APPS.MYKUBE.KARMALABS.COM
    - $(IPA_SERVER_REALM)
    # TODO Define variable IPA_SERVER_CA_SUBJECT
    # - --ca-subject=CN=freeipa-SgD5xAV, O=APPS.MYKUBE.KARMALABS.COM
    - --ca-subject=$(IPA_SERVER_CA_SUBJECT)
    # TODO Define variable IPA_SERVER_DISABLE=ntp,sshd,ssh
    - --no-ntp
    - --no-sshd
    - --no-ssh
    # - --verbose
    # envFrom:
    #   - name: IPA_SERVER_HOSTNAME
    #     configMapRef:
    #       name: config

    env:
    - name: KUBERNETES
      value: "1"
    # - name: KRB5_TRACE
    #   value: /dev/console
    # - name: SYSTEMD_LOG_LEVEL
    #   value: debug
    # - name: SYSTEMD_LOG_COLOR
    #   value: "no"
    # - name: INIT_WRAPPER
    #   value: "1"
    # - name: DEBUG_TRACE
    #   value: "1"
    # - name: DEBUG
    #   value: "1"
    - name: IPA_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: IPA_ADMIN_PASSWORD
          name: freeipa
          optional: false
    - name: IPA_DM_PASSWORD
      valueFrom:
        secretKeyRef:
          key: IPA_DM_PASSWORD
          name: freeipa
          optional: false
    - name: IPA_SERVER_HOSTNAME
      value: $(IPA_SERVER_HOSTNAME)
    # - name: container_uuid
    #   value: b01e51533bce49ce92b6bd4680edd46e
    - name: SYSTEMD_OFFLINE
      value: "1"
    - name: SYSTEMD_NSPAWN_API_VFS_WRITABLE
      value: network
    ports:
    - containerPort: 80
      name: http-tcp
      protocol: TCP
    - containerPort: 443
      name: https-tcp
      protocol: TCP
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1500m
        memory: 3Gi
    securityContext:
      capabilities:
        add:
        - CHOWN
        - FOWNER
        - DAC_OVERRIDE
        - SETUID
        - SETGID
        # Without FSETID the ccache files created has the permissions below:
        #   -rw-rw----. 1 apache apache 3464 Nov 23 21:00 host~freeipa.apps.crc.testing@APPS.CRC.TESTING-z0WzhM
        # With FSETID the ccache files created has the permissions below:
        #   -rw-------. 1 ipaapi ipaapi 5068 Nov 23 21:12 host~freeipa.apps.crc.testing@APPS.CRC.TESTING-YQgWH4
        # In both cases the /run/ipa/ccaches directory has the permissions: drwsrws---+
        #
        # The running process has effective uid:gid=ipaapi:ipaapi so FSETID makes the files
        # to inherit the owner and group from the directory because the set-user-id and set-group-id
        # are set for the directory that contain them.
        #
        # Without FSETID capability the ccache files created are not accessible by the wsgi process
        # evoking the kerberos authentication to fail. It evoked sssd client installation step to
        # fail too as in the step is invoked a RPC method on the wsgi service that has to be
        # authenticated.
        - FSETID
        - KILL
        - NET_BIND_SERVICE
        - SETPCAP
        - SETFCAP
        - SYS_ADMIN
        - SYS_RESOURCE
        drop:
        - NET_RAW
        - SYS_CHROOT
        - AUDIT_CONTROL
        - AUDIT_READ
        - BLOCK_SUSPEND
        - DAC_READ_SEARCH
        - IPC_LOCK
        - IPC_OWNER
        - LEASE
        - LINUX_IMMUTABLE
        - MAC_ADMIN
        - MAC_OVERRIDE
        - NET_ADMIN
        - NET_BROADCAST
        - SYS_BOOT
        - SYS_MODULE
        - SYS_NICE
        - SYS_PACCT
        - SYS_PTRACE
        - SYS_RAWIO
        - SYS_TIME
        - SYS_TTY_CONFIG
        - SYSLOG
        - WAKE_ALARM
        - SYS_RAWIO
        - MKNOD
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    # https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/
    # https://www.freedesktop.org/software/systemd/man/systemd.html#SIGRTMIN+3
    lifecycle:
      preStop:
        exec:
          command: ["kill", "-RTMIN+3", "1"]
    tty: true
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /tmp
      name: systemd-tmp
    - mountPath: /var/run
      name: systemd-var-run
    - mountPath: /var/run/dirsrv
      name: systemd-var-dirsrv
  volumes:
  - emptyDir: {}
    name: data
  - emptyDir:
      medium: Memory
    name: systemd-var-run
  - emptyDir:
      medium: Memory
    name: systemd-var-dirsrv
  - emptyDir:
      medium: Memory
    name: systemd-run-rpcbind
  - emptyDir:
      medium: Memory
    name: systemd-tmp
