---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: freeipa
  name: freeipa-web
spec:
  ports:
  - name: https-tcp
    port: 443
    protocol: TCP
    targetPort: https-tcp
  selector:
    app: freeipa
  sessionAffinity: None
  type: ClusterIP
