---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freeipa
spec:
  template:
    spec:
      containers:
      - name: main
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        emptyDir: {}
