apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../single-pod
- pvc.yaml

patchesStrategicMerge:
- pod-main-patch.yaml

# The 'namespace' field is updated automatically by the Makefile file
# Use OCP_NAMESPACE env variable for changing this
namespace: freeipa
