---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  selector:
    matchLabels:
      app: freeipa

