apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../config-base

patchesStrategicMerge:
- patch-statefulset.yaml

images:
- name: workload
  newName: quay.io/freeipa/freeipa-openshift-container
  newTag: latest
