apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-https.yaml
- route-https.yaml

configMapGenerator:
- envs:
  - env.properties
  name: config

secretGenerator:
- envs:
  - secrets.properties
  name: freeipa
  type: Opaque

vars:
- fieldref:
    fieldPath: data.IPA_SERVER_HOSTNAME
  name: IPA_SERVER_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: config
- fieldref:
    fieldPath: data.IPA_SERVER_REALM
  name: IPA_SERVER_REALM
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: config
- fieldref:
    fieldPath: data.IPA_SERVER_CA_SUBJECT
  name: IPA_SERVER_CA_SUBJECT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: config

configurations:
- kustomizeconfig.yaml

images:
- name: workload
  newName: quay.io/freeipa/freeipa-openshift-container
  newTag: latest
