---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freeipa
spec:
  template:
    spec:
      containers:
      - name: main
        volumeMounts:
        - name: freeipa-data
          mountPath: /data

  volumeClaimTemplates:
  - metadata:
      name: freeipa-data
    spec:
      volumeMode: Filesystem
      volumeName: freeipa
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
